const resources = [
  {
    type: "test",
    event: "Write It Do It",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWE1pVUxFZ0ZQX1k/view?usp=sharing&resourcekey=0-zv_ITKb9sFjPvktdT3U7tA",
    key: "https://drive.google.com/file/d/0By856O3q58sGVmRSMEVRUXlXbmM/view?usp=sharing&resourcekey=0-GPBs-Zzb7MGfhCtZOexpvQ",
  },
  {
    type: "test",
    event: "We've Got Your Number",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGV2JxVkxvQUE1VUk/view?usp=sharing&resourcekey=0-Hne6LxmZnb37wrLnXJfv6Q",
  },
  {
    type: "test",
    event: "We've Got Your Number",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGN3dQeFozaERBLVE/view?usp=sharing&resourcekey=0-tFANeNgqFATDWYTk79XsWw",
  },
  {
    type: "test",
    event: "Water Quality",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGS3YxNHVmSVRDMEk/view?usp=sharing&resourcekey=0-EvVvW-eFEZUvbfSCiWhpPw",
    key: "https://drive.google.com/file/d/0By856O3q58sGTkpIT0djUU40NkU/view?usp=sharing&resourcekey=0-hmnOawYFXBtG_ws4NsK76A",
  },
  {
    type: "test",
    event: "Technical Problem Solving",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMk9fR1JaX29yTnM/view?usp=sharing&resourcekey=0-f5HX78rCclsVc5uYaEyGtg",
    key: "https://drive.google.com/file/d/0By856O3q58sGYmIxV09SVFJTQ0U/view?usp=sharing&resourcekey=0-COGbq4vbmTlW9OFrR-yr1Q",
  },
  {
    type: "scoresheet",
    event: "Storm the Castle",
    year: "2011-2012",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVGJZSlhVZFQ1Q28/view?usp=sharing&resourcekey=0-9Y0XfJ4ryWInyliv3SEkAw",
    key: "https://drive.google.com/file/d/0By856O3q58sGVF9yY2JCN3VVbEk/view?usp=sharing&resourcekey=0-pwYH_Tjf-KQ7Uzbrgc54og",
  },
  {
    type: "scoresheet",
    event: "Scrambler",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVlUtbEpYcHpyYzQ/view?usp=sharing&resourcekey=0-FY0Ybs947-40ONo_1TEZ7A",
  },
  {
    type: "test",
    event: "Science Word",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGREhpSVV5NDdTLVk/view?usp=sharing&resourcekey=0-3Mia_WlNY28mqVuPlDUzyQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGTUVla2ZxQ1F3ZWs/view?usp=sharing&resourcekey=0-lmJsR4ao6DOo5O6I9OWuRw",
  },
  {
    type: "test",
    event: "Rocks and Minerals",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGYmVORXVhY1kzeVk/view?usp=sharing&resourcekey=0-kiHH96VCpvnyrC1cq5b8vQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGbVNiUG11SUJOOWc/view?usp=sharing&resourcekey=0-Z_vXS8ESH_xo4qhbQxYa4w",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Mission Possible",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaV9OWUJ4SC01RHM/view?usp=sharing&resourcekey=0-Gk7UAiUnXY4hIf5GJtTfSA",
  },
  {
    type: "test",
    event: "Mission Possible",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZm5qLWRlNXBIdnM/view?usp=sharing&resourcekey=0-LXOVk6mYilzN1ClVpoMKPA",
  },
  {
    type: "test",
    event: "Material Science",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGbDV6TnNyMjRTYXM/view?usp=sharing&resourcekey=0-Ut86lvvU_sgmNMshO_64cg",
    key: "https://drive.google.com/file/d/0By856O3q58sGZTF4cmdJLUJ5NU0/view?usp=sharing&resourcekey=0-rX2kZT2Qi25b3aavGKF-FA",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Mag Lev",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGOTl2SjBBaHNmcjA/view?usp=sharing&resourcekey=0-rz_plMG6x2sdq6xY2GjprQ",
  },
  {
    type: "test",
    event: "Mag Lev",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGczVvcXFzMUF5dXc/view?usp=sharing&resourcekey=0-yIYIjzGto39Kqq5budAl-A",
    key: "https://drive.google.com/file/d/0By856O3q58sGRmNFVUExSlMzQW8/view?usp=sharing&resourcekey=0-lKOHA2PaZKO8xhBykN7CMQ",
  },
  {
    type: "test",
    event: "GeoLogic Mapping",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVWZxZUljbm9PN1U/view?usp=sharing&resourcekey=0-OPINZBBfiLnnUGmsexk9iw",
    key: "https://drive.google.com/file/d/0By856O3q58sGd1FINmdFeTBjcHM/view?usp=sharing&resourcekey=0-uRwPN589IoEfeGd6Evlpmg",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGVzlIb2ZYRzN2OG8/view?usp=sharing&resourcekey=0-wk1Krjtbq6S0evi8GUeAAg",
  },
  {
    type: "test",
    event: "Fossils",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGcHdYT3A5TjNNUFE/view?usp=sharing&resourcekey=0-yp0qnHdp8zfrRvOvzvXOMQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGckV0XzJuUEtvNHc/view?usp=sharing&resourcekey=0-AX7n6afDUKWfp2UU-UmshQ",
    notes: "missing images",
  },
  {
    type: "test",
    event: "Forensics",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWGEtS1BJS1Z2V2M/view?usp=sharing&resourcekey=0-XZH0Wxah9TE_j15SbvEaMA",
    key: "https://drive.google.com/file/d/0By856O3q58sGc0ZUbE5aYlFnZGM/view?usp=sharing&resourcekey=0-PGp0mHctkG55pwA-Gg3XYA",
  },
  {
    type: "test",
    event: "Fermi Questions",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVUFGZHVxX3ZoRkU/view?usp=sharing&resourcekey=0-Qp80ba5wC21D78nPbjaDgg",
    key: "https://drive.google.com/file/d/0By856O3q58sGaHpINjFMX3VJNTA/view?usp=sharing&resourcekey=0-6yQD8ZOV2SgiIOJt8bMkhw",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGWDBPNlk4ck5NcUE/view?usp=sharing&resourcekey=0-MbDkfARs6vXyD_9DKZpmiw",
  },
  {
    type: "test",
    event: "Experimental Design",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGTldJQjRibWh3TWc/view?usp=sharing&resourcekey=0-iki_hf0zdtvNWxbTmsvkwg",
    key: "https://drive.google.com/file/d/0By856O3q58sGQ2VsbGExX1Z4dEE/view?usp=sharing&resourcekey=0-H67FGUD8VYMxIDmcOcLLfA",
  },
  {
    type: "test",
    event: "Entomology",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGellNVDg5WkJuWXM/view?usp=sharing&resourcekey=0-gH4VoWxvHxX55c_3NeIL6w",
    key: "https://drive.google.com/file/d/0By856O3q58sGSmtHVm9yYVQtRnM/view?usp=sharing&resourcekey=0-5jiH9292WlpKR7vR_gFfYg",
    notes: "missing images",
  },
  {
    type: "scoresheet",
    event: "Elastic Launch Glider",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGRjlKSVltOHhzZ1k/view?usp=sharing&resourcekey=0-PxW3UuN5-YQcguSHw8O4Zg",
  },
  {
    type: "test",
    event: "Dynamic Planet",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWl96cUFFMzBDRFk/view?usp=sharing&resourcekey=0-Dda8kvD0hWt36-8UABEN_g",
    key: "https://drive.google.com/file/d/0By856O3q58sGdFM5V3lSMi11SUE/view?usp=sharing&resourcekey=0-LjxIFVyrMtkySNgONQtMtw",
  },
  {
    type: "test",
    event: "Disease Detectives",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGRGdpcXNpZjZvb0k/view?usp=sharing&resourcekey=0-FQI3D2jb-bQbeY4ATl2scQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGeVI4M09uZjRoWDg/view?usp=sharing&resourcekey=0-MwjUlDyRwJUbHRPUwTEn1g",
    notes: "this is a corrected version",
  },
  {
    type: "test",
    event: "Designer Genes",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVG9Bd3VtVWptbTQ/view?usp=sharing&resourcekey=0-fampr7j8Ri8KqDfZl6oJ9g",
    key: "https://drive.google.com/file/d/0By856O3q58sGa2lPYnIxZ2hBbDg/view?usp=sharing&resourcekey=0-JQcebn3zFLQPGhTTKN0g2Q",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGM1NLVEZIZTNxajQ/view?usp=sharing&resourcekey=0-_u7pW1Z7zivGxx50GW9MDg",
  },
  {
    type: "test",
    event: "Compound Machines",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGU2dKbHhjeU9abTg/view?usp=sharing&resourcekey=0-N7Zo1yEX6YgFh57rjuTjig",
    key: "https://drive.google.com/file/d/0By856O3q58sGOXF1OVlESDNtX2M/view?usp=sharing&resourcekey=0-MJ3Rf19Oq9KJ4W3VaDC3MA",
  },
  {
    type: "scoresheet",
    event: "Compound Machines",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZjZ2NGtUSFM0WEk/view?usp=sharing&resourcekey=0-gf61x1QXS_6WsHGRw63aCg",
  },
  {
    type: "test",
    event: "Circuit Lab",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGUzE3akg4dm5LNzA/view?usp=sharing&resourcekey=0-fShuB9ACVdohMGv-2kMCqg",
    key: "https://drive.google.com/file/d/0By856O3q58sGcGhGdTNSbXVoNDg/view?usp=sharing&resourcekey=0-2YUTXOSze3CP3dZ9KFLzCg",
  },
  {
    type: "test",
    event: "Chemistry Lab",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGbkRGZVk5N0RibXc/view?usp=sharing&resourcekey=0-F_wUjfrGIweL3fw6psWM9Q",
    key: "https://drive.google.com/file/d/0By856O3q58sGYkVzc3E1eFJUVFU/view?usp=sharing&resourcekey=0-CSKcaXY2wqFZTXoIkfpQbQ",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Bungee Drop",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGeW1kTmdVU2hvYUk/view?usp=sharing&resourcekey=0--tC3iZ3lpFQpt5REoLnD5w",
  },
  {
    type: "scoresheet",
    event: "Boomilever",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMHRtZnFTamVnZTg/view?usp=sharing&resourcekey=0-T9PEltPrW9lquf2GCdrtpg",
  },
  {
    type: "test",
    event: "Astronomy",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGdnRwRm9XVEdTUTQ/view?usp=sharing&resourcekey=0-DVwz2PA-dy0L5k4chChtjQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGMjcxZE1EVW5GNGc/view?usp=sharing&resourcekey=0-askvYjasTdi0Mxpy8waWsg",
  },
  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGa3psZThmNVVDQW8/view?usp=sharing&resourcekey=0-SEfpSmGVg_x6lyVLnBoLGQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGV0puZll5dHpQSDQ/view?usp=sharing&resourcekey=0-n_JXFCwHRZMfZDXrdozMMQ",
    notes: "Also the New York State Science Olympiad Regional of 2014",
  },
  {
    type: "test",
    event: "Write It Do It",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGYlNOMnBGVm14STg/view?usp=sharing&resourcekey=0-DiS1dDLGjvMJF1MVeauq-Q",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGVTNFSEc0aUt4WEU/view?usp=sharing&resourcekey=0-Ri2DjZSqyMSH0Tp52C5hUA",
      "https://drive.google.com/file/d/0By856O3q58sGV0w2eXFSV2ZPc1E/view?usp=sharing&resourcekey=0-WzOLMYSUvuNUmReJxvwSQQ",
      "https://drive.google.com/file/d/0By856O3q58sGNnhnNE0tS3BIclE/view?usp=sharing&resourcekey=0-7sg3rYih4w2VzOzmhVrxVw",
      "https://drive.google.com/file/d/0By856O3q58sGY1NIQ1JMbWNjcjQ/view?usp=sharing&resourcekey=0-utcRc0mzpRfzqNkLgAAznQ",
      "https://drive.google.com/file/d/0By856O3q58sGUmM2Nlh2NXFMd1E/view?usp=sharing&resourcekey=0-_kgigDzRjpEMKTHD5X_0XA",
      "https://drive.google.com/file/d/0By856O3q58sGaWd1d2d2SVQ3VlU/view?usp=sharing&resourcekey=0-FyFYSm_hal1M2dra3WNQKg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGOEpLQnZzOFpWRms/view?usp=sharing&resourcekey=0-_vIEZBiVScBOoisWayDUMQ",
    notes: "structure images in additional links",
  },
  {
    type: "test",
    event: "Technical Problem Solving",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGcUhLSDZtbmw4NDQ/view?usp=sharing&resourcekey=0-k-zKF_diODKAayIk3X9Ijw",
    key: "https://drive.google.com/file/d/0By856O3q58sGbUZnbjJEMktHMFU/view?usp=sharing&resourcekey=0-TxOby2iRhg39dZt6J3rfIw",
    notes: "missing lab",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGWE1EQkJtcFpiTEk/view?usp=sharing&resourcekey=0-ChbiMsHmvp-yijcPWb5u_A",
  },
  {
    type: "test",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZnRJRWpmWU5Ybms/view?usp=sharing&resourcekey=0-0zmmWgZXe1SiG48qPaiMxA",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbkhwZXczaWZ0Yjg/view?usp=sharing&resourcekey=0-SXhZBtT9YfbGAiAmckmyDg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGeUJ0Yy1tT29BQVU/view?usp=sharing&resourcekey=0-vBEvFZvbL_wBmYza46ab9Q",
    notes: "Lab portion link below",
  },
  {
    type: "scoresheet",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMEdPVHMyY2dONjQ/view?usp=sharing&resourcekey=0-4ZP7tba6Dbb8WbyDp0bKsA",
  },
  {
    type: "test",
    event: "It's About Time",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSm5CcVZmbkVhWWM/view?usp=sharing&resourcekey=0-XTz3RlZ9WdYJiTVebAcsIg",
    key: "https://drive.google.com/file/d/0By856O3q58sGQWJrbXBHMkJITHM/view?usp=sharing&resourcekey=0-xaKEkrblWiPmBiKllMfAHA",
  },
  {
    type: "test",
    event: "Green Generation",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMVFFcEcwNFlSSVE/view?usp=sharing&resourcekey=0-pnKo0MXUxKejyYahQc4KnA",
    key: "https://drive.google.com/file/d/0By856O3q58sGUkNiRFRFVmk5eUk/view?usp=sharing&resourcekey=0-RuSHxpA52105jzZ3GIDtgQ",
    notes: "structure images in additional links",
  },
];
